### PR TITLE
Add tagName prop and return null from Translation

### PR DESCRIPTION
**Pull request by harrison**
You can now set `tagName` prop on `Message`, `Translation`, `InlineMessage`, `LinkExists`. Also changed `Translation` to return `noscript` node when it shouldn't be rendered.

### CODE REVIEW

**Comment by harrison** [comment]
@Ken-Lo what do you think?

@jamesshedden wanan review?

**Comment by Ken-Lo** [comment]
@harrison This is epic!

Three quick thoughts:

1. This would be a massive breaking change, but worth it also be worth renaming `<LinkExists>` to `<IfLinkExists>`? Would enhance the readability somewhat. e.g.:
     `<IfLinkExists to='jobs' tagName='li'>`
2. Potential further enhancement to legibility (though not sure if it's actually possible to do in JS)? [JSX namespacing](https://github.com/facebook/react/pull/760) e.g. 

    ```jsx
  <IfLinkExists.li to='jobs'>
    Jobs
  </IfLinkExists.li>
    ```
Benefit is it keeps `li` in the name of the tag (more similar to what you expect when writing HTML). Downside is it's probably harder to implement (also not sure if Javascript supports overloaded functions)?
3. I think `<Message>` shouldn't be allowed to set a `tagName` or create new tags (it's only supposed to be used in an inline context anyway.)
e.g. this is confusing to read:

    ```jsx
<ul>
  <Message tagName='li' pointer='blah' />
  <Message tagName='li' pointer='blahblah' />
</ul>
```
or
    ```jsx
  <p><Message tagName='strong' pointer='phone_local' /></p>
```
(would be better to just specify this explicitly around the `<Message />` tag)

**Comment by harrison** [comment]
Yeah `IfLinkExists` makes more sense, also removed `tagName` from message.
Namespaces could work with some funky getter to support arbitrary tagnames, but would want to play around with it before implementing.

**Comment by Ken-Lo** [comment]
:+1: Nice one, loving this change!

Will leave it to you, @jamesshedden, to review :)

**Comment by jamesshedden** [comment]
@harrison Awesome, :+1: from me!

**Pull request merged**
