### PR TITLE
Add AUDDIS Direct Debit landing page

### PR DESCRIPTION
**Pull request by Ken-Lo**
auddis page

### CODE REVIEW

**Comment by Ken-Lo** [comment]
Hey @swillis 
Would you kindly be able to have a look at this?:) Also, for the first two sections we're struggling to find a relevant image... any thoughts on what might work best on this page?
Thanks!

**Comment by swillis** [comment]
Hey @Ken-Lo, thanks for this, having a look now :smile:

**Comment by Ken-Lo** [comment]
Thanks @swillis - let me know if you have any thoughts!

**Comment by swillis** [comment]
@Ken-Lo: Hey! Just been looking through this and largely it looks good :smile:

There are a few bits and pieces that still need addressing, so I was wondering if you fancied sitting down on Monday and over it together?

**Comment by Ken-Lo** [comment]
Hey @swillis 
Would you mind taking another look?:)
Thanks!

**Comment by swillis** [comment]
@jamesshedden quick look when you get a mo? :ok_hand:

**Pull request merged**
