### PR TITLE
Adding French timeline & payment page images

### PR DESCRIPTION
**Pull request by jamesshedden**
screen shot 2015-06-05 at 15 46 03

### CODE REVIEW

**Comment by jamesshedden** [comment]
@octaveauger @adeclosset Looks good? :eyes:

**Comment by octaveauger** [comment]
@jamesshedden perfect!

**Comment by jamesshedden** [comment]
@octaveauger Awesome, merged :+1:

**Comment by adeclosset** [comment]
You're the best James!

On 5 June 2015 at 16:51, James Shedden <notifications@github.com> wrote:

> @octaveauger <https://github.com/octaveauger> Awesome, merged [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/191#issuecomment-109318089>
> .
>



-- 

gocardless.fr | gocardless.com

T: +33 (0) 9 75 18 85 40 | +44 (0) 2036 370 591

M: +33 (0) 6 71 79 50 36 | +44 (0) 7538 648 006

Ils parlent de GoCardless: Le Figaro
<http://www.lefigaro.fr/societes/2015/04/12/20005-20150412ARTFIG00171-gocardless-pret-a-bousculer-les-banques-francaises.php>
 | Les Echos
<http://www.lesechos.fr/finance-marches/banque-assurances/0213743712-le-prelevement-bancaire-seduit-de-nouveaux-acteurs-1110875.php>
 | Challenges
<http://www.challenges.fr/finance-et-marche/20150413.CHA4873/ces-start-up-qui-font-valser-les-modeles-de-la-city-de-londres.html>
 | La Tribune
<http://www.latribune.fr/entreprises-finance/banques-finance/gocardless-ou-quand-la-fintech-londonienne-debarque-en-france-469023.html>
 | Journal du net
<http://www.journaldunet.com/web-tech/start-up/fintech-gocardless-lancement-france.shtml>

**Pull request merged**
