### PR TITLE
Halve the sticker price for SEPA Pro

### PR DESCRIPTION
**Pull request by greysteil**
We talked about doing this a couple of weeks ago.

Do not merge until existing customers have been informed and had their fees reduced.

### CODE REVIEW

**Comment by greysteil** [comment]
@octaveauger - are you managing this one?

**Comment by octaveauger** [comment]
@adeclosset should handle it

**Comment by anothertompetty** [comment]
Hey @octaveauger @greysteil looking to get open PRs merged before starting work on new splash pages for Pro. Any updates on this badboy?

**Comment by greysteil** [comment]
Closing after discussion offline.

**Pull request closed without merging**
