### PR TITLE
made fixes and edits to stories pages

### PR DESCRIPTION
**Pull request by sjnorth**
made fixes and edits to stories pages

### CODE REVIEW

**Comment by sjnorth** [comment]
@Ken-Lo

**Comment by Ken-Lo** [comment]
:+1: Great work!

**Comment by Ken-Lo** [comment]
@jamesshedden just fyi, thanks! :)

**Comment by jamesshedden** [comment]
@Ken-Lo @sjnorth Awesome, nice work ⚡

**Pull request merged**
