### PR TITLE
Add Spanish press coverage to homepage

### PR DESCRIPTION
**Pull request by Ken-Lo**
Add press coverage to Spanish homepage

### CODE REVIEW

**Comment by clippy** [comment]
**I have manually checked the visuals in:**

- [ ] Chrome
- [ ] IE11
- [ ] Firefox
- [ ] Safari
- [ ] iPad

**Comment by Ken-Lo** [comment]
Fyi @carlesmarcos @AlfonsoSB

**Comment by AlfonsoSB** [comment]
Perfect! Thanks @Ken-Lo 

We will soon have 2 new articles to publish :)

**Comment by Ken-Lo** [comment]
Nice one @AlfonsoSB @carlesmarcos - you guys are on fire with your content atm :-)

**Pull request merged**
