### PR TITLE
Legal translation

### PR DESCRIPTION
**Pull request by AlfonsoSB**
I have translated the restricted activities list, and also the
summaries in legal. @greysteil

### CODE REVIEW

**Comment by AlfonsoSB** [comment]
@greysteil @harrison Whenever you can! Thanks

**Comment by greysteil** [comment]
^^^ That was me.

**Comment by AlfonsoSB** [comment]
I'm just doing what the other teams have done, translate the restricted activities and the summary of the legal terms. 
The restricted activities is important as I have already have a couple of merchants that have asked. 
However, I just realised that there is a newer restricted activities list. I'm updating it right now
Get Outlook for mobile




On Sun, Feb 21, 2016 at 2:49 AM -0800, "Gobot" <notifications@github.com> wrote:












Code looks good. Are we fine to translate our legal pages like this, though? Does it have Ahmed's approval?

**Comment by AlfonsoSB** [comment]
@greysteil @harrison Whenever you can merge, it is ready!

**Comment by greysteil** [comment]
:+1:

**Pull request merged**
