### PR TITLE
Remove Head of Sales: Germany ad

### PR DESCRIPTION
**Pull request by gabrielamatias**
@harrison , @waltfy : I have removed the only role in the German jobs page. I seem to be missing some change, but I am not an expert in javascript to get to the bottom of this. Can one of you take a look at why tests fail and why removing the last role in the german jobs page causes the (german) page to not render?

Seems to be related to this here: https://github.com/gocardless/splash-pages/blob/dev/app/pages/about/jobs/jobs.js#L16

### CODE REVIEW

**Comment by waltfy** [comment]
@gabrielamatias I've pushed something up that fixes your issue. Just needed to remove the german jobs page as a whole.

**Comment by gabrielamatias** [comment]
@waltfy : am I ok to merge? Thank you so much!

**Comment by waltfy** [comment]
@gabrielamatias you should probably squash these commits? Let me know if you don't know how to do that and I can help you out.

**Comment by gabrielamatias** [comment]
@waltfy : I have no idea, but @nlopes says he can teach me. Thank you!

**Comment by gabrielamatias** [comment]
@waltfy : please review.

**Comment by waltfy** [comment]
@gabrielamatias once it goes green it should be good to go. Great work! 👍

**Pull request merged**
