### PR TITLE
[DO NOT MERGE] Add generic splash pages for Europe in English

### PR DESCRIPTION
**Pull request by Ken-Lo**
First stab at a generic set of splash pages in English.

**Homepage:**

screen shot 2015-05-18 at 19 03 56

**Pro Page:**

screen shot 2015-05-18 at 19 04 04

**Pricing Page:**

screen shot 2015-05-18 at 19 04 12

### CODE REVIEW

**Comment by Ken-Lo** [comment]
Hey @octaveauger 
Would be great if you could let me know your thoughts on the European/Irish splash pages. Have tried translating a lot of what you guys did on the early French SEPA splash pages.
Would also be good to get your help on the following sections if possible:
* FAQ > Direct Debit (needs updating to be about SEPA)
* FAQ > Customer Experience (needs updating to be about SEPA)
* FAQ > International Payments (needs updating to be about SEPA)
* FAQ > Developer API (needs updating for GC Pro)
Thanks!

**Comment by Ken-Lo** [comment]
@harrison fyi, so you can see what we've been translating the pages.

@octave-auger @adeclosset Mind taking a final look to see if there's anything else we need to do before merging?

**Comment by harrison** [comment]
Before merging this you will need to close this pr and open it again against `dev`

**Comment by Ken-Lo** [comment]
@harrison Good spot, will do that now!

**Pull request closed without merging**
