### PR TITLE
Update FCA notice

### PR DESCRIPTION
**Pull request by jacobpgn**
We've been advised to slightly change the wording here. 

@adeclosset @jutta-frieden could you please provide translations to reflect the change?

### CODE REVIEW

**Comment by adeclosset** [comment]
@jacobpgn Done in French!

**Comment by jacobpgn** [comment]
Vielen gracias, @adeclosset !

**Comment by jacobpgn** [comment]
Merci @jutta-frieden!

@jamesshedden Would you mind taking a quick peek?

**Comment by jamesshedden** [comment]
@jacobpgn :+1: :+1: :+1: :+1: :+1:

**Comment by jacobpgn** [comment]
:boom:

**Pull request merged**
