### PR TITLE
update sandbox-signup link

### PR DESCRIPTION
**Pull request by samjewell**
Point sandbox signup to `manage-sandbox.gocardless.com/signup`

### CODE REVIEW

**Comment by harrison** [comment]
Nice :+1: is the signup tested for sandbox or is it all the same flow as prod?

**Comment by samjewell** [comment]
@harrison Not sure I understand - do you mean the end-to-end integration tests that we run, and get emails about if/when they fail?

**Comment by harrison** [comment]
Ignore, was thinking if we did any special casing for signups in prod/sandbox but seems like it's just the same flow!

**Comment by harrison** [comment]
on the backend

**Pull request closed without merging**
