### PR TITLE
Removing job ads

### PR DESCRIPTION
**Pull request by jesssummerfield**
@petehamilton please can you check this?

@gabrielamatias fyi

### CODE REVIEW

**Comment by jesssummerfield** [comment]
@petehamilton can't figure why the checks failed, please can you help with this as well?? Thanks!!

**Comment by petehamilton** [comment]
@jesssummerfield, think you just need to remove CCM role from routes.js

**Comment by jesssummerfield** [comment]
@petehamilton sorted now!

**Comment by petehamilton** [comment]
LGTM :+1:

**Pull request merged**
