### PR TITLE
[DO NOT MERGE] Updating German Splash Pages

### PR DESCRIPTION
**Pull request by Ken-Lo**
Do not merge: Still requires update & translation into German.

- Adds SEPA Guide link to German homepage
- Add German features page
- Show 1% pricing in Germany

### CODE REVIEW

**Comment by Ken-Lo** [comment]
@jutta-frieden Copying over the English features page into Germany, etc. Would be great if you could pick up from here?
Thanks!

**Comment by jutta-frieden** [comment]
Hi @georg911 could you help us proof-read the new German copy once again? The pages adapted are the homepage and the new .../de-de/features/ page. Please ignore the English table for now, this will be added later today/tomorrow. Thank you!

**Comment by jutta-frieden** [comment]
@georg911 I also translated the product comparison table now. Happy for you to scan with a second pair of German eyes :-) Thank you!

**Comment by georg911** [comment]
@jutta-frieden Alles klar wie Kloßbrühe! :-) Looking good!

**Pull request merged**
