### PR TITLE
De - add picdrop and crossfit case study

### PR DESCRIPTION
**Pull request by jutta-frieden**
Added first two German case studies. This still requires input from design team before we can merge.

### CODE REVIEW

**Comment by clippy** [comment]
**I have manually checked the visuals in:**

- [ ] Chrome
- [ ] IE11
- [ ] Firefox
- [ ] Safari
- [ ] iPad

**Comment by jutta-frieden** [comment]
@georg911 quick scan of German if possible? Please merge if all good!
@swillis your images in action! Thanks again 👍

**Comment by georg911** [comment]
@jutta-frieden perfekt!

**Comment by jutta-frieden** [comment]
Awesome, thanks @georg911 !

On Friday, 6 May 2016, georg911 <notifications@github.com> wrote:

> Merged #514 <https://github.com/gocardless/splash-pages/pull/514>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/514#event-652317010>
>


-- 
---
Jutta Frieden
jutta.frieden@gmail.com
+44 7428214431

**Pull request merged**
