### PR TITLE
Fix sandbox signup links

### PR DESCRIPTION
**Pull request by isaacseymour**
(German ones are fixed in #227 )

@samjewell could you review?

### CODE REVIEW

**Comment by samjewell** [comment]
Awesome work man, thanks so much for this! :-) :+1:

**Comment by samjewell** [comment]
kudos to @isaacseymour for cleaning up after me!

**Comment by samjewell** [comment]
BOOM!

**Comment by isaacseymour** [comment]
Going to deploy this manually as Circle is down

**Pull request merged**
