### PR TITLE
Added legal pages, cookie disclaimer in footer and updated a couple of links

### PR DESCRIPTION
**Pull request by octaveauger**
@samjewell fyi this new branch should fix the issue with the old one
@jamesshedden this replaces the old branch (which doesn't need to be merged now). I've added:
- the French legal pages (not happy about the bottom of "mentions legales", the list doesn't render nicely but I don't want bullet points)
- one line in the footer about the cookie disclaimer,
- one more link in the footer to the sepa guide (which breaks a bit the link display: 4 on line 1, 1 on line 2)
- and a couple of fixes in FAQ and about pages (mostly updated links)
@adeclosset fyi

### CODE REVIEW

**Comment by samjewell** [comment]
WOOP! Good work fixing up the git history :-)
Would you mind dropping in a screenshot of the things you're not so happy about, so we can see what might need fixing?

**Comment by octaveauger** [comment]
The footer (left section): having only one link on the second row feels out of balance.
screen shot 2015-02-03 at 15 34 56
The Softlayer bit appears differently because I used a list without any class, instead of using br tags.
screen shot 2015-02-03 at 15 35 08

**Comment by jamesshedden** [comment]
@octaveauger 

Hey, this might be nicer for the footer now there's enough links:

screen shot 2015-02-03 at 18 17 16

For the SoftLayer details, I used a `.u-color-p` utility class to just keep it the same colour as the paragraphs:

screen shot 2015-02-03 at 18 21 29

I've pushed these changes so do a `git pull` next time you work on this branch :+1:

**Comment by jamesshedden** [comment]
PS @octaveauger code looks good, you can merge when you're happy with final content :+1:

**Comment by octaveauger** [comment]
@samjewell @harrison after talking to Sam I've merged dev into this branch and updated the flag. On my side it's all good to go.

**Comment by jamesshedden** [comment]
@octaveauger @samjewell Nice one chaps, merged :+1:

**Pull request merged**
