### PR TITLE
Added Basic Pro contract on French legals

### PR DESCRIPTION
**Pull request by adeclosset**
Hey - Adding the UK contract (legal/merchants) on the French website with a few tweaks (mainly presence of SEPA, absence of customer account). More context in a separate email.

@octave-auger : I have translated the intro in French. Can you check? 
@harrison : first time adding a page, so might be worth checking I did it right.

### CODE REVIEW

**Comment by harrison** [comment]
Looks good :+1:

You using sublime? There are a bunch of linting errors about mixed tabs/spaces and end of line spaces. You can have these fixed in sublime with the `editorconfig` package. Happy to help with this.

**Comment by adeclosset** [comment]
Yes I do, but I'm indeed a bit confused about conventions around end of line. Help appreciated :)

Also uploading a screenshot for @octave-auger

**Comment by octaveauger** [comment]
@adeclosset fixed it, good to go from my side

**Comment by adeclosset** [comment]
Merged & closed like a big boy!

**Comment by greysteil** [comment]
:boom:

**Pull request merged**
