### PR TITLE
Enable signup in Ireland 🍀

### PR DESCRIPTION
**Pull request by petehamilton**
That. As Erez put it: "Let's test the waters."

@isaacseymour could you do the honours? Anything I've forgotten?

CC @alan @greysteil @jackfranklin @matt-thomson @erezmt

### CODE REVIEW

**Comment by matt-thomson** [comment]
https://www.youtube.com/watch?v=rE49ca6j754

**Comment by petehamilton** [comment]
Do Not Merge (just yet). Tested and there's a postal code bug I didn't spot before :(

**Comment by alan** [comment]
It's a big week for Ireland, they are getting postal codes and access to GC

**Comment by isaacseymour** [comment]
I'm pretty sure this is all that's needed. :+1: assuming you've fired it up and had a click through.

**Comment by petehamilton** [comment]
Yup. This is good to go once https://github.com/gocardless/payments-service/pull/4626 is merged in

**Pull request merged**
