### PR TITLE
changes Europe text throughout the site

### PR DESCRIPTION
**Pull request by angusbayley**
@anothertompetty I'm happy with this but you're welcome to change anything if you think of better wording

### CODE REVIEW

**Comment by angusbayley** [comment]
@octaveauger

**Comment by octaveauger** [comment]
@angusbayley I removed "Pro" as the goal of this page is to register interest, whether we can serve them now or not, and build a list of inbound leads for now or later when we can actually serve them.

@anothertompetty let us know if you have any feedback or if we can merge

**Comment by angusbayley** [comment]
:+1:

**Comment by anothertompetty** [comment]
LGTM :+1:

**Pull request merged**
