### PR TITLE
Remove IT technician job ad

### PR DESCRIPTION
**Pull request by gabrielamatias**
@jacobpgn : please review.

### CODE REVIEW

**Comment by jacobpgn** [comment]
👍

**Comment by Ken-Lo** [comment]
@gabrielamatias @jacobpgn Just a reminder if we could to add deleted pages to `/config/redirects.json` (otherwise they don't actually get deleted from the website!)

**Comment by gabrielamatias** [comment]
Could you explain it to me when you're in the office? I don't really know
how to do it :)

**Comment by Ken-Lo** [comment]
@gabrielamatias No problem, I will come and find you tomorrow morning :-)

**Pull request merged**
