### PR TITLE
International holding page [Don't merge]

### PR DESCRIPTION
**Pull request by jamesshedden**
A holding page design for upcoming locales, involving:

- Adding new locales
- Adding new holding page design
- Refactoring existing home page component to include new locales & holding page component

To do:
- [ ] Flags for new locales
- [ ] Translated, localised content, probably inside the `HomeHoldingPage` component
- [ ] Email success messages/screens - no designs for how these would appear for this particular page at the moment
- [ ] Confirming email form is hooked up properly
- [ ] Domain forwarding (eg `gocardless.se` -> `gocardless.com/se-se/`, not sure off the top of my head if we need to do anything for that in this repo)
- [ ] Any necessary testing

the easy way to collect recurring payments gocardless

New list of locales (some without flags, see above todo list):

screen shot 2015-09-23 at 18 37 11

### CODE REVIEW

**Comment by clippy** [comment]
**Adding new CSS?**

If you're adding a new component, make sure your naming of both the filename and classes is consistent and follows our conventions:

Here's what's :+1::

```
/* hero.css */

/* The parent class for your component */
.hero {}

/* Child elements denoted by double undescore */
.hero__image {}

/* Modified versions (which should still depend on their unmodified counterparts)
denoted by double hyphen */
.hero__image--large {}
```

Here's what's :-1::

```
/* page-hero.css */

/* Doesn't match filename */
.hero {}

/* Parent-child relationship suggested by hyphen instead of double underscore */  
.hero-image {}

/* No, just no. */
.hero-image__large {}
```

**Changing existing CSS?**

Make sure you know that your changes to existing CSS aren't having any adverse or unexpected consequences across the app you're working with - this should involve tracking down *any* instance of the class, tag or otherwise that you're changing and checking it out locally to make sure everything looks :ok_hand:.

The way things appear affects how GoCardless is perceived - think more "Tech? Internet? We got this!" and less "Your money is safe with us, probably".

**Comment by Ken-Lo** [comment]
@jamesshedden Fyi, just merged in the latest version of dev (with new flags - see https://github.com/gocardless/splash-pages/pull/303). Also did some minor re-factoring with a new country property for whether to show a holding page.

**Comment by anothertompetty** [comment]
@Ken-Lo @nicola-gc any word on what's happening with this? We probably shouldn't just leave it here in purgatory

**Comment by Ken-Lo** [comment]
@swillis Hey Sam! When you get a spare mo, would you mind adding in the flags for Australia, Brazil and New Zealand? Thanks!

**Pull request closed without merging**
