### PR TITLE
Add german partner guide [Don't merge]

### PR DESCRIPTION
**Pull request by jutta-frieden**
German partner guide, note that we left out one of the pages ("Non-UK payments")

### CODE REVIEW

**Comment by jutta-frieden** [comment]
@jamesshedden As discussed, could you ensure that /app/pages/partners/guide/partners-guide-page.js gets amended so the title "Partnering with GoCardless" can be translated too? In German, that would be "Werden Sie Partner von GoCardless"

**Comment by jutta-frieden** [comment]
@georg911 A lot of proof-reading, but could you have a look at the German when you get some free time please?

**Comment by jamesshedden** [comment]
Awesome work @jutta-frieden !

I'll schedule some time in over the next couple of days to take a look at this for you.

I added a `[Don't merge]` label to the Pull Request title which is something we usually do to indicate something's definitely a work in progress, and not something that could technically be merged in right at this moment. Not the end of the world that you didn't have it but just thought I'd mention! :)

Great stuff! :zap:

**Comment by jutta-frieden** [comment]
Good shout @jamesshedden Will keep this in mind for the next time!
Thanks for taking a look. :+1:

**Comment by jamesshedden** [comment]
@jutta-frieden Hey, have pushed up my changes so that partners guide is currently looking like this:

image

image

**Comment by jutta-frieden** [comment]
Ah perfect, thanks @jamesshedden Are you the best person to look over rest of code?
@georg911 you just give thumbs up when you've had a chance to look over the :de: ok?

**Comment by jamesshedden** [comment]
@jutta-frieden Yes probably! I'll take a look :+1:

**Comment by jamesshedden** [comment]
@jutta-frieden Looks good - epic pull request & awesome work!

What I'd recommend is having a good click around your new German guide, and also the existing English one, as we've changed the way it's all hooked up slightly as part of this work, just to make sure it's all working together correctly - aside from that, :+1:

**Comment by georg911** [comment]
Hey @jutta-frieden, I've added some minor corrections above. Otherwise all good

**Comment by jutta-frieden** [comment]
Awesome thank you @georg911 and @jamesshedden All ready to go then :)

**Pull request merged**
