### PR TITLE
Amendments to API & Developer Pages

### PR DESCRIPTION
**Pull request by Ken-Lo**
* Remove scrollbars from code sample on Windows PCs
* Remove unneeded 'Contact Sales' button from middle of API page
* On API page, change guide at bottom to read 'Developer Documentation' and to point towards the Developer landing page

### CODE REVIEW

**Comment by clippy** [comment]
**I have manually checked the visuals in:**

- [ ] Chrome
- [ ] IE11
- [ ] Firefox
- [ ] Safari
- [ ] iPad

**Comment by Ken-Lo** [comment]
Hey @megaslug 
Just some further changes from Polly and I - also removing the scrollbars from the code samples as we discussed previously :)
Thanks!

**Comment by megaslug** [comment]
@Ken-Lo looks good!

**Comment by Ken-Lo** [comment]
Thanks @megaslug!

**Pull request merged**
