### PR TITLE
Rewriting front end developer job ad

### PR DESCRIPTION
**Pull request by harrison**
Changing from front end designer to front end developer emphasising developer chops more than design skills.

### CODE REVIEW

**Comment by harrison** [comment]
@jamesshedden review?

**Comment by jamesshedden** [comment]
@harrison Nice work :+1:

**Comment by Ken-Lo** [comment]
@harrison Nice one - don't forget `redirects.json` as well or the old page also remains online (we currently have hundreds of old job adverts - would be great to delete these at some point)

**Comment by harrison** [comment]
@Ken-Lo nice catch!

**Pull request merged**
