### PR TITLE
Description of how to use fb-flo, for realtime updates to the page when you save.

### PR DESCRIPTION
**Pull request by samjewell**

### CODE REVIEW

**Comment by samjewell** [comment]
@adeclosset @octaveauger @angusbayley not sure if you guys have installed fb-flo, but it's worth it - to see your changes update live in the browser...

**Comment by samjewell** [comment]
@harrison quick check if you like?

**Comment by angusbayley** [comment]
thanks @samjewell !

**Comment by harrison** [comment]
:+1:

**Pull request merged**
