### PR TITLE
New German Homepage

### PR DESCRIPTION
**Pull request by Ken-Lo**
screen shot 2016-07-25 at 15 30 14

### CODE REVIEW

**Comment by clippy** [comment]
**I have manually checked the visuals in:**

- [ ] Chrome
- [ ] IE11
- [ ] Firefox
- [ ] Safari
- [ ] iPad

**Comment by Ken-Lo** [comment]
@jutta-frieden Your new homepage :) Please feel free to pull down and make changes!

**Comment by jutta-frieden** [comment]
screen shot 2016-07-29 at 11 20 07
screen shot 2016-07-29 at 11 20 16
screen shot 2016-07-29 at 11 21 36

**Comment by jutta-frieden** [comment]
@georg911 Can you have a look through German wording please?
@swillis would be great if we could add the image for betahaus here. Can do this in a separate step though!
Thanks both

**Comment by georg911** [comment]
All 🇩🇪  looks sexy! good to go @jutta-frieden

**Pull request merged**
