### PR TITLE
Ask SEPA merchants for the country they're interested in

### PR DESCRIPTION
**Pull request by greysteil**
form

### CODE REVIEW

**Comment by greysteil** [comment]
@maxmurdoch - can you review?

**Comment by greysteil** [comment]
@adeclosset - FYI. This information won't be displayed anywhere though - for that I'll need some salesforce help from @alinagator

**Comment by maxmurdoch** [comment]
@greysteil :+1: good to go

**Comment by adeclosset** [comment]
@maxmurdoch @greysteil Hey guys, tried to make the changes myself, but getting the picklist is proving too difficult. 

The salesforce object we need to tie in is Country__c (see picture, link here https://eu2.salesforce.com/00Nb0000009e7PZ?setupid=LeadFields). I don't know how to take the Salesforce Country__c object, get it in picklist format with the values set-up in SF.

The text should say: Where is your company based?

screen shot 2015-01-22 at 12 37 10

**Comment by alinagator** [comment]
Not sure if this helps, but I think SF will accept any value on leads that
are pushed to it (even if it doesn't appear on the SF picklist) - so you
could just use a standard picklist from somewhere (that's how I originally
got the countries in SF). We'd need to test this - Tim and I discovered
this behaviour by accident a couple of months ago, but SF have a habit of
changing validation-related stuff.

Give me a shout if I can help with anything!

P.S. I've changed my github notification settings, so I shouldn't be
missing mentions in future ;)

On 22 January 2015 at 12:40, Amaury de Closset <notifications@github.com>
wrote:

> @maxmurdoch <https://github.com/maxmurdoch> @greysteil
> <https://github.com/greysteil> Hey guys, tried to make the changes
> myself, but getting the picklist is proving too difficult.
>
> The salesforce object we need to tie in is Country__c (see picture, link
> here https://eu2.salesforce.com/00Nb0000009e7PZ?setupid=LeadFields). I
> don't know how to take the Salesforce Country__c object, get it in picklist
> format with the values set-up in SF.
>
> The text should say: Where is your company based?
>
> [image: screen shot 2015-01-22 at 12 37 10]
> <https://cloud.githubusercontent.com/assets/8441794/5855742/738b451e-a233-11e4-801d-2a77290991a8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/389#issuecomment-71014593>
> .
>



-- 
Alina Solovjova
0203 397 4316

GoCardless <http://www.gocardless.com/> | 338-346 Goswell Rd, London, EC1V
7LQ

**Comment by adeclosset** [comment]
This is not urgent, but should be done. @timrogers, do you want to take it when you're back?

**Comment by greysteil** [comment]
@adeclosset - mate, I've got a broken hand and lots of things going on. Easy on the chasing or you'll be doing these yourself in future! ;)

**Comment by greysteil** [comment]
@adeclosset - updated

**Pull request merged**
