### PR TITLE
Add features video to FR/DE/ES features page

### PR DESCRIPTION
**Pull request by Ken-Lo**
**France**

screen shot 2016-07-11 at 12 05 34

**Germany**

screen shot 2016-07-11 at 14 25 30

**Spain**

screen shot 2016-07-11 at 12 06 04

### CODE REVIEW

**Comment by Ken-Lo** [comment]
Hey @comegocardless @sebastiengocardless @jutta-frieden @AlfonsoSB 
Would you guys mind reviewing?:)
Thanks!

**Comment by AlfonsoSB** [comment]
Seems perfect! @Ken-Lo

**Comment by sebastiengocardless** [comment]
All good for me

On Mon, 11 Jul 2016 at 16:47 Alfonso SB <notifications@github.com> wrote:

> Seems perfect! @Ken-Lo <https://github.com/Ken-Lo>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/568#issuecomment-231775782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOgZ3pr5NeIJSUT0demz6z0VLEKXGtN-ks5qUmWPgaJpZM4JJQgM>
> .
>
-- 
Sebastien Cromback
GoCardless

gocardless.fr | gocardless.com
F: +33 (0) 9 70 73 12 79
Ils parlent de GoCardless: Le Figaro | Les Echos | Challenges | La Tribune
| Journal du net ᐧ

**Comment by Ken-Lo** [comment]
Thanks guys! Let me know if the German looks ok @jutta-frieden and we can get this live :-)

**Pull request merged**
