### PR TITLE
Adding include for team list

### PR DESCRIPTION
**Pull request by jamesshedden**
We're repeating the list of team members in a couple of places now so makes sense to use an include:

screen shot 2015-02-19 at 15 41 48
screen shot 2015-02-19 at 15 41 58

### CODE REVIEW

**Comment by jamesshedden** [comment]
@moyni :heart:

**Comment by jamesshedden** [comment]
@samjewell Fancy giving this a quick review Sammy J? :sunglasses:

**Comment by moyni** [comment]
Dreamy.

**Comment by samjewell** [comment]
hell yeah, this is sick! LGTM

**Pull request merged**
