### PR TITLE
Fr tutoriel revamp

### PR DESCRIPTION
**Pull request by adeclosset**
Hello,

Here is a big revamp of the tutorial to update images and content. Also, a big chunk on verification and payment tracking have been added.

Out of scope: adding plans and paylink (will do in another branch)

@comegocardless @sebastiengocardless @octaveauger - can you check for typos and comment here?

### CODE REVIEW

**Comment by adeclosset** [comment]
Screenshot of the two articles most modified:

screencapture-localhost-4402-fr-fr-faq-tableau-de-bord-pro-suivi-paiements-1461673549649

screencapture-localhost-4402-fr-fr-faq-tableau-de-bord-pro-1461673571279

**Comment by adeclosset** [comment]
@Ken-Lo - Hey Kin-Hing, could you check if all is good? Looks like it's a green-light test-wise.

**Comment by Ken-Lo** [comment]
:+1: Only thing I noticed was that some of the screenshots have your autocomplete manager - but no biggie (can remove only if you think it's worth doing).

**Comment by adeclosset** [comment]
@Ken-Lo oh damn you are right. Let me adjust.

**Comment by adeclosset** [comment]
@Ken-Lo - done!

**Comment by Ken-Lo** [comment]
:+1: nice work!

**Pull request merged**
