### PR TITLE
Update about us page

### PR DESCRIPTION
**Pull request by jesssummerfield**
@english please can you check this one too?

### CODE REVIEW

**Comment by english** [comment]
@jesssummerfield Do you want me to just check that the code looks good? Has this copy gone been reviewed by a few people?

**Comment by jesssummerfield** [comment]
@english just code please, @gabrielamatias and I have checked with mgmt and design on content :)

**Comment by english** [comment]
Sorry for the delayed review! Looks good :+1:

**Comment by jesssummerfield** [comment]
@english thank you!

**Pull request merged**
