### PR TITLE
Add industries dropdown

### PR DESCRIPTION
**Pull request by Ken-Lo**
screen shot 2016-06-30 at 11 44 36

### CODE REVIEW

**Comment by Ken-Lo** [comment]
Hey @swillis @jamesshedden 
Would you guys mind reviewing?:) Would be great if you guys could also have a quick look through the industry pages, so we can make sure the styles are consistent before linking to the pages from the main website.
/cc @nicola-gc 
Thanks!

**Comment by jamesshedden** [comment]
@Ken-Lo Hey, thanks for this!

I was curious looking at this as I remembered the site analysis we did after implementing these splash pages in 2014 — we found that almost no one (I think about 1% of visitors) clicked through to the vertical pages from the dropdown from the home page, which led to us getting rid of it — be good to get your thoughts on reasons for bringing it back.

**Comment by swillis** [comment]
Hey @Ken-Lo, we chatted to Nicola earlier about this to get some more context. Happy for you to merge in once you've squashed the commits into one message 👍 Let me know if you need any help with this at all.

**Comment by Ken-Lo** [comment]
I've just merged this in [here](https://github.com/gocardless/splash-pages/commit/742c46b4746ed87fba6163e51030ec6b8895d228) - not sure why the PR hasn't updated.

**Pull request closed without merging**
