### PR TITLE
Updated title & description + remove Pro mentions

### PR DESCRIPTION
**Pull request by adeclosset**
@octaveauger want to check & merge?

### CODE REVIEW

**Comment by octaveauger** [comment]
@adeclosset proofreading done
@samjewell @greysteil this is purely content change to harmonise the content across the site now that we have a homepage. Can you merge to dev?

**Comment by adeclosset** [comment]
@greysteil  - FYI merging this pull request, only content changes

**Comment by samjewell** [comment]
:-D

**Comment by greysteil** [comment]
:+1: on the process on this one :)

**Pull request merged**
