### PR TITLE
darken the background of invert-hollow buttons

### PR DESCRIPTION
**Pull request by samjewell**
# (when active)
## from this
screen shot 2015-06-22 at 17 42 49

## to this
screen shot 2015-06-22 at 17 43 23

### CODE REVIEW

**Comment by samjewell** [comment]
@anothertompetty would you take a look at this one? Thanks mate :-D

**Comment by samjewell** [comment]
@jamesshedden would you mind giving this a review? Not sure what happened to @anothertompetty

**Comment by jamesshedden** [comment]
@samjewell Hey man, nice stuff - what was the thinking behind this? Did we use to have it on old splash-pages and got missed out, or just a design idea of yours?

**Comment by samjewell** [comment]
No idea if it was on the old splash pages - probably not actually, I think I might have checked the wayback machine. Mainly a design idea - I thought it looked really ugly with the solid blue as the active state

**Comment by jamesshedden** [comment]
Ah ok cool! For stuff like this it's awesome if you can include the
reasoning in the PR description - GitHub is great at showing the "how" but
the "why" is equally important (if not possibly more so) for design
decisions - hope that makes sense!

I'd err against this change for now - on the move now but happy to chat
thru this when I'm in.

On Wednesday, 24 June 2015, Sam Jewell <notifications@github.com> wrote:

> No idea if it was on the old splash pages - probably not actually, I think
> I might have checked the wayback machine. Mainly a design idea - I thought
> it looked really ugly with the solid blue as the active state
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/219#issuecomment-114980330>
> .
>


-- 
*James Shedden*
js@gocardless.com
07976001458

**Comment by jamesshedden** [comment]
@samjewell Closing this for now following our discussion :+1:

**Pull request closed without merging**
