### PR TITLE
Belgian (Dutch) Splash Pages

### PR DESCRIPTION
**Pull request by JoeriVankeirsbilck**
First version of the Belgian (Dutch) Splash Pages, and various
corrections to the Dutch Splash Pages.
@greysteil @harrison

### CODE REVIEW

**Comment by greysteil** [comment]
@jamesshedden - I know Phil's stacked with reviews, can you take a quick look?

**Comment by harrison** [comment]
:+1:

**Comment by greysteil** [comment]
:tada:

**Comment by JoeriVankeirsbilck** [comment]
Great, thanks team!

On 15 December 2015 at 14:03, Grey Baker <notifications@github.com> wrote:

> [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/352#issuecomment-164774034>
> .
>



-- 
*Joeri Vankeirsbilck*
Country Lead The Netherlands & Belgium
NL +31 85 888 7620 | Gocardless.nl <http://www.gocardless.nl>
BE +32 78 483 075 | Gocardless.be <http://www.gocardless.be>
UK +44 20 3744 3259 | m +44 77 2976 7567

**Pull request merged**
