### PR TITLE
Improve the formatting of monthly collections options

### PR DESCRIPTION
**Pull request by timrogers**
As requested by @nicola-gc.

### CODE REVIEW

**Comment by timrogers** [comment]
@Ken-Lo Can you give this a quick look? :smile: Just making the options a bit nicer to read.

**Comment by Ken-Lo** [comment]
:+1: Looks good Tim! Do we need to add in the options as a locale-specific message (just thinking about European countries that use `.` as a thousands separator)

**Comment by timrogers** [comment]
@Ken-Lo Is this PR needed anymore after #727?

**Comment by Ken-Lo** [comment]
Hey @timrogers 
I made my PR against your branch, so yes, this one still needs to be merged in to dev! :-)

**Pull request merged**
