### PR TITLE
Added and updated homepage for France - WIP v1

### PR DESCRIPTION
**Pull request by adeclosset**
:warning: Do not merge

@octave-auger This is the branch to add the French homepage. This is in WIP, still quite a bit of work. Let's work on it Monday.

### CODE REVIEW

**Comment by adeclosset** [comment]
@octaveauger Can you check the French content before we involve UX?

**Comment by octaveauger** [comment]
@anothertompetty 
Can you take a look? We had to integrate a few design elements from other pages (e.g the user quotes).
Also what'd be ideal is if we could use a different symbol for "fait pour le récurrent" (that shows it's made for recurring payments) and replace the GBP symbol by a EUR equivalent.
We'd also like to use the guide image (https://gocardless.com/guides/images/guide-sepa@2x.jpg) but in French: what do you think?

@adeclosset fyi

**Comment by octaveauger** [comment]
With screenshot
homepage screenshot

**Comment by octaveauger** [comment]
@samjewell @jamesshedden can you merge? I've changed the logos to versions that, although are not 100% amazing, make sense.

@Ken-Lo @adeclosset fyi

**Comment by samjewell** [comment]
### Pretty sure that https://github.com/gocardless/guides/pull/164 depends on this PR (amirite?)

**Comment by jamesshedden** [comment]
@octaveauger @adeclosset Cool, given this a quick once-over and merged, nice work :+1:

**Comment by octaveauger** [comment]
cheers!

**Pull request merged**
