### PR TITLE
Add international holding pages

### PR DESCRIPTION
**Pull request by Ken-Lo**
A holding page for upcoming locales. Replaces https://github.com/gocardless/splash-pages/pull/297.

screen shot 2015-12-31 at 01 57 28

Country selector dropdown:

screen shot 2015-12-31 at 01 58 41

**To do:**

- [x] Add copy for all locales
- [x] Confirm email form is hooked up correctly
- [x] Add flags for Australia, Brazil and New Zealand
- [x] Translate the Brazil holding page into Portugese
- [x] UX review

### CODE REVIEW

**Comment by clippy** [comment]
**I have manually checked the visuals in:**

- [ ] Chrome
- [ ] IE11
- [ ] Firefox
- [ ] Safari
- [ ] iPad

**Comment by Ken-Lo** [comment]
Hey @swillis - Would you mind helping me out with adding the flags for Australia, Brazil and New Zealand?

@waltfy Could you kindly help us with translating the Brazilian splash pages into Portuguese? The two files we need to translate are:
https://github.com/gocardless/splash-pages/blob/international-holding-page/app/messages/pt.js and
https://github.com/gocardless/splash-pages/blob/international-holding-page/app/messages/pt-BR.js

@jamesshedden Apart from that, should all be good to go from our side, though would be great if you could review the design & code!

Thanks all!

**Comment by swillis** [comment]
Hey @Ken-Lo, I've added the new flag icons :smile: 

Couple of things I noticed (which you may be aware of already, apologies if so!):

- We have *België* and *Belgique* when we probably want one or the other.
- Sometimes we label the languages in English and sometimes we don't (*España* vs. *France*). Should we pick one or the other and stick with it?

Otherwise, looking good! :earth_africa: :+1:

**Comment by Ken-Lo** [comment]
@swillis Gracias, very much appreciated!

* België is for Flemish region of Belgium and Belgique is for the French region :-)
* In French, France is still France!

**Comment by waltfy** [comment]
@Ken-Lo quick update just to let you know that I'm working on the translations and should have something soon-ish! :)

Thanks.

**Comment by swillis** [comment]
@Ken-Lo aha, I see! I was thinking of *French*/*Francais*.

Does that mean Sweden should be different?

**Comment by jamesshedden** [comment]
@Ken-Lo Nice work! Will schedule some time to take a look at design/code this week :zap:

**Comment by Ken-Lo** [comment]
@waltfy Thank you for adding the translations!

@jamesshedden Thanks so much!

@swillis Yes - it'll be 'Svenska' when we get round to launching Swedish-language splash pages :-) Currently the splash pages for Sweden are only in English!

**Comment by waltfy** [comment]
@Ken-Lo I'm just finishing up the `pt.js` translations today, as discussed. There are still some missing parts.

**Comment by Ken-Lo** [comment]
Hey @jamesshedden 
Just wondering if you guys managed to get some time to look through this PR last week? Let me know if there's anything I can do this week to help get it to completion!
Thanks!

**Comment by jamesshedden** [comment]
@Ken-Lo Sorry for delay looking at this, was only in a few days last week so didn't manage to look at it, apologies - all done now, looks good :+1:

**Comment by Ken-Lo** [comment]
Thanks @jamesshedden! :earth_americas:

**Pull request merged**
