### PR TITLE
Tidying up Spanish Splash Pages

### PR DESCRIPTION
**Pull request by Ken-Lo**
Tidying up from https://github.com/gocardless/splash-pages/pull/311.

**Things to double-check:**
* I changed the e-mail address from Spain@ to spain@ - please verify this is correct.
* Added a local phone number: 091 198 1220 - please verify this is in the right format?

**Things to do:**

* On the homepage, "Precios simples y transparentes para todo el mundo" is a little bit too long... is it possible to get this down to only one line?
screen shot 2015-10-19 at 12 49 26
* The Features page still has a timeline & screenshots in English. Can we at least get a screenshot of the payment page in Spanish? e.g. like we have in [France](https://gocardless.com/fr-fr/fonctionalites/):
fr payment page
* The three headline benefits on the Features page looks a bit weird - can we try and get them so they're of a more similar length?
screen shot 2015-10-19 at 12 50 34
* Would be good to try and tidy up the pricing page so both sides of the table line up:
screen shot 2015-10-19 at 12 51 16

### CODE REVIEW

**Comment by Ken-Lo** [comment]
Hey @AlfonsoSB
Could you have a quick look at the things I've listed above? 
Thanks!

**Comment by AlfonsoSB** [comment]
@Ken-Lo Hello
1. The email is Ok. It's better to put the capital letter, but that is only my opinion.
2. The phone is wrong. I thought I had already put it in the right format but there is no 0 in Spain. It should start with +44 
3. Precios Simples y Transparentes para todo el mundo. We could take out the "Simples", and "todo el mundo" for "Todos". So it would be "Precios transparentes para todos"
4. Payment page, yes, we can do it but I don't have any logo for now, unless we can use Techhub without asking them.
5. & 6. Lining up things is very difficult sometimes. I have tried and succeeded in most occasions but in those 2 is really difficult unless we change the meaning. Depending on how important is to line up.

thanks

**Comment by Ken-Lo** [comment]
Thanks Alfonso!

@jamesshedden Could you have a quick look and let me know if this payment page screenshot looks OK?

screen shot 2015-10-22 at 10 56 57

Thanks!

**Comment by AlfonsoSB** [comment]
Yes. It's great. thanks!

**Comment by jamesshedden** [comment]
@Ken-Lo Looks good, although looks like the vertical alignment is a bit off ie the top of the image on the right is much lower than the top of the text on the left, if that makes sense?

**Comment by Ken-Lo** [comment]
Thanks @AlfonsoSB @jamesshedden - just removed the margin from the image.

screen shot 2015-10-22 at 12 48 11

**Comment by jamesshedden** [comment]
@Ken-Lo Nice :+1:

**Pull request merged**
