### PR TITLE
Add number of payments dropdown to en-GB contact sales

### PR DESCRIPTION
**Pull request by Ken-Lo**
Add number of payments dropdown to en-GB contact sales

screen shot 2015-11-09 at 19 25 31

### CODE REVIEW

**Comment by Ken-Lo** [comment]
@benmiller169 Could you share this with Joe as well? This puts the "number of payments" drop down menu back on the en-GB contact sales page.

@timrogers Wondering if you'd be able to check if the backend is set up to receive this information? Have just copied this over from the French Contact Sales page so I presume this should already be set up to collect the information?

**Comment by benmiller169** [comment]
fyi

-- 
*Ben Miller*
Account Executive
GoCardless
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2z93wjW7fsMg27dSGy4W4X9Hq256dWhdf15yBXK02?t=https%3A%2F%2Fgocardless.com%2F&si=6203636223836160&pi=4098fed2-d11a-42e8-de5b-2b47bc786371>
020 3637 2047
<http://t.sidekickopen03.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2z93wjW7fsMg27dSGy4W4X9Hq256dWhdf15yBXK02?t=http%3A%2F%2Fuk.linkedin.com%2Fpub%2Fben-miller%2F45%2F523%2Fa03&si=6203636223836160&pi=4098fed2-d11a-42e8-de5b-2b47bc786371>

**Comment by Ken-Lo** [comment]
Hey @harrison Could you kindly review the code? I think gocardless should still be set up to receive this information?

**Comment by harrison** [comment]
:+1: should work, looks like it's already on the french one

**Comment by Ken-Lo** [comment]
Thanks Phil!

**Pull request merged**
