### PR TITLE
Add german splash pages

### PR DESCRIPTION
**Pull request by jutta-frieden**
For the German translations, we updated the following pages for now:
- home
- pro
- partner
- pricing
- about & team
- impressum

Things to look out for are typos, German grammar mistakes and bad formulations. Furthermore, let's test that all links are working fine. If you can think of anything else, please test it too :-) Thank you!

screen shot 2015-05-28 at 15 58 04

screen shot 2015-05-28 at 15 58 51

screen shot 2015-05-28 at 15 59 11

### CODE REVIEW

**Comment by jutta-frieden** [comment]
@georg911 Here you go! Thank you so much!

**Comment by harrison** [comment]
Wow nice work!

**Comment by Ken-Lo** [comment]
@jutta-frieden Amazing work! Btw, just added screenshots to the pull request in case anyone is interested in seeing how the pages look :)

**Comment by jackfranklin** [comment]
kudos to @jutta-frieden, this is awesome! :de: :de:

**Comment by georg911** [comment]
http://192.168.1.150:4402/de-de/preise/
Implementierung kostenlos? Ich lese das so, als ob GC mir meine Integration bastelt. 

http://192.168.1.150:4402/de-de/pro/
"Wir speichern alle Bank Details mittels RSA Verschlüsselung..."
Anstatt Bank Details vielleicht Bankverbindungen?

"Registrieren Sie sich für einen gratis Testaccount."
Der Link führt direkt zum sign-up, vielleicht "Registrieren Sie sich einen gratis Testaccount."?

@jutta-frieden Super! Just found these three notes, nothing really important/dramatic.

**Pull request merged**
