### PR TITLE
Link to Iain's blog post from internship job details

### PR DESCRIPTION
**Pull request by greysteil**
That.

### CODE REVIEW

**Comment by greysteil** [comment]
@jackfranklin - can you review?
@iainnash - FYI!

**Comment by jackfranklin** [comment]
Would it be better if it was clearer the link goes to a specific post ? Currently reads as if it just links generally to the blog.

How about:

```
If you'd like to know more about an internship at GoCardless, Iain, one of our previous interns, <a href='...'>wrote a post on the GoCardless blog</a> on his internship.
```

Fairly pedantic, happy to be disagreed with!

**Comment by greysteil** [comment]
@jackfranklin - don't love that phrasing. How about one big link (updated)?

**Comment by jackfranklin** [comment]
:+1:

**Pull request merged**
