### PR TITLE
Use if locale tags part two

### PR DESCRIPTION
**Pull request by Ken-Lo**
Update the rest of the splash pages to use `<IfLocale> tag.

### CODE REVIEW

**Comment by Ken-Lo** [comment]
@harrison This is mainly a bunch of content re-factoring, though if possible I wanted to get your thoughts on pricing.en.js. https://github.com/gocardless/splash-pages/commit/ecb2108fd815511aaa49a018dc441d121b78b19b#diff-7ee5a44d2f67da2f1b6a41fb9a4255b7

The issue is: we need to show different CSS classes depending on whether % pricing is available (`.grid__cell .u-size-1of2` if % pricing available, otherwise just `.grid__cell`). Not sure what's the cleanest way of doing this in the code -- comparing `this.context.messages` in `render()`?

**Comment by Ken-Lo** [comment]
@octaveauger @adeclosset Just an fyi so you guys can see how we're using the new tags & how they differ from normal `<Translation>`. 

Good examples:
* [Use of &lt;IfLocale domesticScheme='x'&gt;](https://github.com/gocardless/splash-pages/pull/214/files#diff-8010c3eb7f940b34078f0c437b116882L59)
  * Makes the code clearer as Creditor ID & SUN link directly to SEPA & Bacs
  * Could easily launch new locales (e.g. English splash pages in any other country)
* [Use of &lt;IfLocale hasInstantSignup&gt;](https://github.com/gocardless/splash-pages/pull/214/files#diff-8010c3eb7f940b34078f0c437b116882L90)
  * Also [here](https://github.com/gocardless/splash-pages/pull/214/files#diff-b517286d52ef39fc0f4454eb33f1a74aL90), [here](https://github.com/gocardless/splash-pages/pull/214/files#diff-7ee5a44d2f67da2f1b6a41fb9a4255b7L95), etc.
  * Makes the code clearer
  * Easy to launch instant sign-up in any country later (won't need to update the list in every file)
* [Use of &lt;IfLocale hasPercentagePricing&gt;](https://github.com/gocardless/splash-pages/pull/214/files#diff-7ee5a44d2f67da2f1b6a41fb9a4255b7L74)
  * Makes the code clearer
  * Easy to launch basic pricing in any country

Let me know if you guys have any further questions (if needed, I can set up another 15 mins to go through this). Would be good to use these when we start localising fr-fr and when content starts to differ from fr-be (e.g. with sign-up flow/CTAs).

**Comment by adeclosset** [comment]
Hey Kin-Hing,

Ok I get it. As this would be a new framework, we should document it very
cleanly. Could you create a Notes page to explain the framework and
different objects?

Else, we will forget about it or not use it consistently.

Best,
Amaury

On 15 June 2015 at 19:48, Ken-Lo <notifications@github.com> wrote:

> @octaveauger <https://github.com/octaveauger> @adeclosset
> <https://github.com/adeclosset> Just an fyi so you guys can see how we're
> using the new tags & how they differ from normal <Translation>.
>
> Good examples:
>
>    - Use of <IfLocale domesticScheme='x'>
>    <https://github.com/gocardless/splash-pages/pull/214/files#diff-8010c3eb7f940b34078f0c437b116882L59>
>       - Makes the code clearer as Creditor ID & SUN link directly to SEPA
>       & Bacs
>       - Could easily launch new locales (e.g. English splash pages in any
>       other country)
>     - Use of <IfLocale hasInstantSignup>
>    <https://github.com/gocardless/splash-pages/pull/214/files#diff-8010c3eb7f940b34078f0c437b116882L90>
>       - Also here
>       <https://github.com/gocardless/splash-pages/pull/214/files#diff-b517286d52ef39fc0f4454eb33f1a74aL90>,
>       here
>       <https://github.com/gocardless/splash-pages/pull/214/files#diff-7ee5a44d2f67da2f1b6a41fb9a4255b7L95>,
>       etc.
>       - Makes the code clearer
>       - Easy to launch instant sign-up in any country later (won't need
>       to update the list in every file)
>     - Use of <IfLocale hasPercentagePricing>
>    <https://github.com/gocardless/splash-pages/pull/214/files#diff-7ee5a44d2f67da2f1b6a41fb9a4255b7L74>
>       - Makes the code clearer
>       - Easy to launch basic pricing in any country
>
> Let me know if you guys have any further questions (if needed, I can set
> up another 15 mins to go through this). Would be good to use these when we
> start localising fr-fr and when content starts to differ from fr-be (e.g.
> with sign-up flow/CTAs).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocardless/splash-pages/pull/214#issuecomment-112151538>
> .
>



-- 

gocardless.fr | gocardless.com

T: +33 (0) 9 75 18 85 40 | +44 (0) 2036 370 591

M: +33 (0) 6 71 79 50 36 | +44 (0) 7538 648 006

Ils parlent de GoCardless: Le Figaro
<http://www.lefigaro.fr/societes/2015/04/12/20005-20150412ARTFIG00171-gocardless-pret-a-bousculer-les-banques-francaises.php>
 | Les Echos
<http://www.lesechos.fr/finance-marches/banque-assurances/0213743712-le-prelevement-bancaire-seduit-de-nouveaux-acteurs-1110875.php>
 | Challenges
<http://www.challenges.fr/finance-et-marche/20150413.CHA4873/ces-start-up-qui-font-valser-les-modeles-de-la-city-de-londres.html>
 | La Tribune
<http://www.latribune.fr/entreprises-finance/banques-finance/gocardless-ou-quand-la-fintech-londonienne-debarque-en-france-469023.html>
 | Journal du net
<http://www.journaldunet.com/web-tech/start-up/fintech-gocardless-lancement-france.shtml>

**Comment by Ken-Lo** [comment]
@adeclosset Will do, thanks!

**Pull request merged**
