### PR TITLE
Added Pro sandbox access for FR page

### PR DESCRIPTION
**Pull request by adeclosset**
@jamesshedden @samjewell Can you guys check if all good?

### CODE REVIEW

**Comment by samjewell** [comment]
Hey @adeclosset can you put up a screenshot too?

**Comment by jamesshedden** [comment]
@adeclosset Looks good :+1:

**Comment by jamesshedden** [comment]
PS Here's what it looks like:

screen shot 2015-02-11 at 10 31 12

FYI @adeclosset When possible we like to include screenshots of visual changes like this in the description of the Pull Request (eg https://github.com/gocardless/splash-pages/pull/398) as it makes reviewing the code even easier, as the reviewer can quickly see where they're supposed to be looking for the changes without having to figure out from the code. 

cc @samjewell

**Comment by adeclosset** [comment]
Ok sorry guys, thanks for the tip!

gocardless.fr | gocardless.com

+33 (0) 9 75 18 42 95 | +44 0 20 3637 0591

**Comment by jamesshedden** [comment]
@adeclosset No problemo! Nice one :+1:

**Pull request merged**
