### PR TITLE
Redirect gocardless.com/de/ to gocardless.com/de-de/

### PR DESCRIPTION
**Pull request by Ken-Lo**
Redirect gocardless.com/de/ to gocardless.com/de-de/

### CODE REVIEW

**Comment by harrison** [comment]
:+1:

**Comment by Ken-Lo** [comment]
@harrison Thanks! I've merged this into dev & master.
One issue: I'm not sure if redirects are being deployed correctly (I'm still getting 404 on https://gocardless.com/de/)

**Comment by harrison** [comment]
Fixing redirects, the file itself wasn't changing on s3 so the new redirect wasn't being updated.

**Comment by Ken-Lo** [comment]
Just a bump, any update on whether redirects are now being updated?
Thanks!

**Comment by harrison** [comment]
Now properly fixed! :)

**Pull request merged**
