### PR TITLE
Re-order restrictions

### PR DESCRIPTION
**Pull request by jacobpgn**
@ahmedbadr3 would you kindly?

### CODE REVIEW

**Comment by jacobpgn** [comment]
@ahmedbadr3 amended as per your comments - could you give it a glance?

**Comment by Ken-Lo** [comment]
@jacobpgn Is this PR still needed?

**Comment by jacobpgn** [comment]
I believe so 😬  @ahmedbadr3 ?

**Comment by ahmedbadr3** [comment]
@jacobpgn did you fix the fails? what about latest branch warning? thanks!

**Comment by Ken-Lo** [comment]
@ahmedbadr3 Bump, shall I merge this in?

**Comment by jamesshedden** [comment]
@jacobpgn @Ken-Lo Hey, any ideas if this is still needed? Be awesome to close if not! 🙏

**Comment by jacobpgn** [comment]
@ahmedbadr3 @ahmedbadr3 @ahmedbadr3 @ahmedbadr3 @ahmedbadr3 @ahmedbadr3 @ahmedbadr3 @ahmedbadr3

**Comment by Ken-Lo** [comment]
:+1: @megaslug code looks good to me

**Pull request merged**
