### PR TITLE
Add landing page for accountants

### PR DESCRIPTION
**Pull request by Ken-Lo**
screen shot 2016-01-14 at 16 07 47

### CODE REVIEW

**Comment by Ken-Lo** [comment]
Hey @jamesshedden 
Any chance you'd be able to review?
Thanks! :-)

**Comment by jamesshedden** [comment]
@Ken-Lo Hey, looks good - few design pointers and screenshot below:

- Testimonial section shouldn't exist with a heading and horizontal rules outside of it (removed in screenshot below)
- Be great to keep logo sizes consistent & balanced with each other (suggested sizes in screenshot below)

image

Let me know if above doesn't make sense - otherwise let me know when you've made the changes and I'll take a look at the final code :+1:

**Comment by Ken-Lo** [comment]
Thanks @jamesshedden! I've taken out the hrs and testimonial headings. Is there any chance you might be able to help us out with the accountancy software logos? Also, I don't suppose you know why ba/container-builder is failing?
Thanks!

**Comment by jamesshedden** [comment]
@Ken-Lo Great stuff, will take a look tomorrow PM :+1:

**Comment by jamesshedden** [comment]
@Ken-Lo Hey, sorry - got sidetracked with stuff today, will try and squeeze in this evening, failing that tomorrow AM :+1:

**Comment by jamesshedden** [comment]
@Ken-Lo Hey, looking at the logos again I think the image you already have should be OK - have looked over the code this morning and all looks :+1:

Re the container builder, I'm unsure - I tried retrying via the `Details` link but doesn't seem to have any effect - perhaps worth getting in touch with one of the platform team or @harrison might know what's up?

Once everything's green, :+1: from me!

**Comment by Ken-Lo** [comment]
Thanks James!

@harrison Just wondering if you had any ideas on why the container image build might be failing? Thanks!

**Comment by harrison** [comment]
@Ken-Lo fixed it, if you rebase dev it should hopefully work:)

**Comment by Ken-Lo** [comment]
@harrison Amazing, thank you!

**Pull request merged**
