### PR TITLE
removal of partnership roles

### PR DESCRIPTION
**Pull request by katie-mai**
@megaslug - removal of both partnership roles. Please check and approve

### CODE REVIEW

**Comment by megaslug** [comment]
@katie-mai since we're removing these two jobs, would be good to add redirects to both of these urls. See `redirects.json`

**Comment by katie-mai** [comment]
@megaslug re redirecting - the are already commands to redirect on redirects.json > lines 4 and 12.

Shall we see if those work before deleting and re adding?

**Comment by megaslug** [comment]
@katie-mai ok, that's cool. it's a bit worrying that they haven't worked

**Comment by megaslug** [comment]
@katie-mai You removed `partnership-marketing-manager.js` and `partnerships-development.js` files, but these don’t match removals in `routes.js`, those are: `partnerships-development.js`, and `partnerships-success.js`

**Pull request merged**
